version: "3.7"
services:
  router_mock:
    image: "routermock:latest"
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - "ROUTER_HTTP_PORT=8081"

  converter_mock:
    image: "convertermock:latest"
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      - "CONVERTER_HTTP_PORT=8082"

