version: "3.7"
services:
  router_mock:
    image: "routermock:latest"
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - "ROUTER_HTTP_PORT=8081"

  router_mock_db:
    image: oscarfonts/h2
    restart: unless-stopped
    ports:
      - "1521:1521"
    environment:
      - "H2_OPTIONS=-ifNotExists"

  converter_mock:
    image: "convertermock:latest"
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      - "CONVERTER_HTTP_PORT=8082"

  converter_mock_db:
    image: oscarfonts/h2
    restart: unless-stopped
    ports:
      - "1522:1522"
    environment:
      - "H2_OPTIONS=-ifNotExists"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_CREATE_TOPICS: "sql-query-actions,sql-query-response"
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  trace_engine:
    image: "trace-engine:latest"
    restart: unless-stopped
    ports:
      - "8083:8083"
    environment:
      TRACE_ENGINE_HTTP_PORT: 8083
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  pump:
    image: "pump:latest"
    restart: unless-stopped
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
