addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.2")
addSbtPlugin("au.com.onegeek" % "sbt-dotenv" % "2.1.227")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.8.1")
addSbtPlugin("io.github.davidgregory084" %% "sbt-tpolecat" % "0.1.17")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.2")
addCompilerPlugin("com.olegpy" %% "better-monadic-for" % "0.3.1")
